# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


n <- 4*10^6
fibonacci_number <- c(1,2,3)
even <- c(0,2,0)
i <- 3

while (fibonacci_number[i] < n) {
    i <- i + 1
    fibonacci_number <- append(fibonacci_number,  fibonacci_number[i - 1] + fibonacci_number[i - 2])
    if (0 == fibonacci_number[i] %% 2) {
        even <- append(even, fibonacci_number[i])
    }

}

sum_even <- sum(even)
sum_even